# Generated by Django 3.2.9 on 2022-06-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='Date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='Name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='swimmer',
            name='Weight',
            field=models.IntegerField(verbose_name='Weight'),
        ),
    ]
